export const INJECTION_TOKENS = {
  SCRAPE_ACTIVITIES_USE_CASE: Symbol.for('SCRAPE_ACTIVITIES_USE_CASE'),
  ACTIVITY_REPOSITORY_PORT: Symbol.for('ACTIVITY_REPOSITORY_PORT'),
  BROWSER_SCRAPER_PORT: Symbol.for('BROWSER_SCRAPER_PORT'),
  BODY_BATTERY_SCRAPER: Symbol.for('BODY_BATTERY_SCRAPER'),
  SLEEP_SCRAPER: Symbol.for('SLEEP_SCRAPER'),
  HOME_SCRAPER: Symbol.for('HOME_SCRAPER'),
  STRESS_SCRAPER: Symbol.for('STRESS_SCRAPER'),
  ACTIVITIES_SCRAPER: Symbol.for('ACTIVITIES_SCRAPER'),
  GARMIN_SCRAPER_COMPOSITE: Symbol.for('GARMIN_SCRAPER_COMPOSITE'),
  ACTIVITY_REPORT_SCRAPER: Symbol.for('ACTIVITY_REPORT_SCRAPER'),
} as const;

export type InjectionToken =
  (typeof INJECTION_TOKENS)[keyof typeof INJECTION_TOKENS];
